apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::293507215039:role/eksctl-eksctl-demo-nodegroup-ng-2-NodeInstanceRole-11QVZKKQD7H1E
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::293507215039:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-22T14:46:21Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1818"
  uid: 17a613dd-7344-42af-9949-0b363bd8a4b1
